### ISSUE TITLE
auto expand closes back to compact every time you edit

### ISSUE THREAD

**Issue by DLPB2** [myst6re/makoureactor#106]
It's very irritating :P

it also returns the cursor position to the top.

**Comment by myst6re** [comment]
Fixed by https://github.com/myst6re/makoureactor/pull/100/commits/f84b15fd25d2bbe177341d03085894c039aec97f and https://github.com/myst6re/makoureactor/pull/100/commits/090f34b6dcb91cdbcc55ed24f261b115feccdd4f
