### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by DLPB2** [myst6re/makoureactor#107]
Program terminates randomly.  One way to replicate is to copy an instruction from one field to another.  Sooner or later the program will die - silently.  No crash handler kicks in.  Happens with or without Opengl being enabled.

**Comment by DLPB2** [comment]
It's crashing pretty much every time I try to access walkmesh on tin_1

**Comment by myst6re** [comment]
Hello, can you tell me which version was used? A dev one or the 1.8.3?

**Comment by DLPB2** [comment]
1.8.3

**Comment by myst6re** [comment]
Should be fixed in the current unstable build
