### ISSUE TITLE
It is not possible to edit window coordinates, width and height in some cases

### ISSUE THREAD

**Issue by Greengoblin007** [myst6re/makoureactor#109]
Example: junonr4, text 26 to 29.

Apparently this happens when there is a script between "Create window" and "Displays the dialogue".

Regards!

**Comment by myst6re** [comment]
It is always possible to edit window coordinates. But the link between a text and its window is not always easy to detect.

**Comment by Greengoblin007** [comment]
I mean the main window:

https://imgur.com/vkUoQvQ

Also I suspect the "Autosize All" option does not work on those particular dialogues.

**Comment by myst6re** [comment]
Maybe I can do something to improve the link detection. Your example does not give me results on my fflevel.lgp, I don't have any text 27, 28 or 29. Can you give me another example? Or just a copy paste of the related lines in the script, thanks!

**Comment by Greengoblin007** [comment]
Sorry, I was using The Reunion R06g flevel.
On original PSX game, a good example is on 4sbwy_3, text 29, 32 and 33.

Regards!

**Comment by myst6re** [comment]
In this example, those 3 texts use the same window. I don't want to edit a window via the text editor, if it have consequences on multiple texts.
