### ISSUE TITLE
Models do not appear in preview window bottom left

### ISSUE THREAD

**Issue by DLPB2** [myst6re/makoureactor#110]
This may be because I'm using the default file override in settings > configuration

J:\FF7\data\field\char.lgp

But that in itself is a bug.  The char lgp file is default and untouched.

**Comment by DLPB2** [comment]
Wait,...  now it's working with 1.8.4
weird

**Comment by myst6re** [comment]
Maybe an issue with OpenGL on your machine, I don't know
