### ISSUE TITLE
Replace text on all fields

### ISSUE THREAD

**Issue by Tsunamods** [myst6re/makoureactor#114]
Using the find and replace feature for text works on a single screen but will not do all fields at once.
My texts on all screens for example look like this:

"Cloud:
  Not Interested"
  
 And I wish to replace "Cloud:" with "Cloud" all at once.

**Comment by myst6re** [comment]
I repaired the existing replace all feature, you can test it with the build here (when available): https://ci.appveyor.com/project/myst6re/makoureactor/builds/40564642/job/6ry735pa1icl2wmf/artifacts
