### ISSUE TITLE
{PAUSE} tags not working. Softocks game.

### ISSUE THREAD

**Issue by TsukiyoX** [myst6re/makoureactor#115]
I tried {PAUSE} and {PAUSE030} and it would just softlock the game with the text not going past where the tag is. I don't really want to put flevel.lgp through touphscript (where the tag does work), since it messes up the widths of boxes.

**Comment by TsukiyoX** [comment]
I did some investigating and found that if I put the tag,{PAUSE030} in Makou Reactor, then dump the texts with touphscript, the tag would appear as {PAUSE 13342}

**Comment by myst6re** [comment]
Maybe 030 is not correctly parsed, thanks for the report!

**Comment by TsukiyoX** [comment]
Of course. And just so you know, I also recently noticed there's no way to place the {OK} tag. The program doesn't recognise the tag when I manually input it, either. Show I create another issue for this?

**Comment by TsukiyoX** [comment]
Ok, I found out that {PAUSE} is the {OK} tag in touphscript.

**Comment by myst6re** [comment]
Just to clarify before closing this issue: {PAUSE} means the text will wait an input before continue to display. And {PAUSEnnn} is a timed pause which last nnn "field time"
