### ISSUE TITLE
Export/Import of current map results in inconsistencies

### ISSUE THREAD

**Issue by LaZar00** [myst6re/makoureactor#116]
I found something odd when doing "Export from current map..." and "Import to current map..." options in menu. Using Windows 10 x64, and Makou 1.8.4 version.

This can be tested doing:
- Open vanilla english flevel.lgp
- Select "mds5_5" field
- Export from current map (compressed) 
- Import to current map. Choose previous export and select/check all the sections.
- Export from current map (compressed) this "new" updated "mds5_5" map (with another name, please).
- Use any tool (like lzs.exe) to uncompress both files.
- Do a binary/hex compare of the files.

It should be the same, but are differences. Mostly in palette section as I've seen.

**Comment by myst6re** [comment]
I found four inconsistencies:

- The AKAO part (in section 1) is not correctly aligned sometimes, that's not a problem in PC version, but can be one in PS version
- The palette header has an incorrect size, I need to add 4 to it
- The palette alpha info in the background header (PC only) has some missing enabled flags, that's should not be a problem, as the game does not parse it completely anyway
- Lot of tile infos have differencies, I need to investigate further on this

**Comment by myst6re** [comment]
For the last item of the list, the PC format is a mess, and I didn't want to save useless things in memory. So when I save the background part, I recreate some data, but that's should not be a problem in the game !

**Comment by myst6re** [comment]
New inconsistency found:

- I added the word "FINAL FANTASY7" at the end of the background section, which is not required, so this section has 14 extra bytes
