### ISSUE TITLE
"LZS bad header" message when importing sections of Uncompressed field.

### ISSUE THREAD

**Issue by LaZar00** [myst6re/makoureactor#117]
Another issue I've seen in Makou 1.8.4 is when you try to import some sections (or all of them) from an **Uncompressed PC Field** to the same field selected after opening the flevel.lgp file.

It results in a "Bad LZS header" message, which it should not happen as it is not lzs compressed.

**Comment by myst6re** [comment]
I think I inverted a flag, will be fixed in the next version
