### ISSUE TITLE
Request: Ability to edit Field Model data for FF7-PS1

### ISSUE THREAD

**Issue by HeyItsLollie** [myst6re/makoureactor#118]
Hi Myst6re,
I was doing [some tests with the directional lighting in FF7-PC](https://forums.qhimm.com/index.php?topic=20540.msg285477#msg285477) during the last weekend, and I wanted to test the directional lighting in FF7-PS1 as well. But Makou Reactor currently locks all of the Field Model data for FF7-PS1. Is it possible to enable these controls?

![Makou_Reactor_20210720_18-27-21-051](https://user-images.githubusercontent.com/30498581/126291518-92852eb1-3948-4aca-9451-25b2795930ff.png)

**Comment by jeromearz** [comment]
Hello, it is not a quick feature to do, so do not expect an implementation of this soon. I don't think it is really hard to make it happen in Makou, if someone can take a look I will gladly accept the PR

**Comment by jeromearz** [comment]
That's something I wanted to do from a long time now, because obviously PC behavior is completely different from the PS one.

**Comment by HeyItsLollie** [comment]
I had a feeling it was disabled due to PS1/PC differences, that's understandable. I mostly just wanted to voice support for the feature!

![Makou_Reactor_20210719_16-39-14-255](https://user-images.githubusercontent.com/30498581/126481842-a09d9fac-fbc3-482e-a479-17b4bc74f55f.png)

The main thing I found in my testing: In the opening scene, if you zero out these values for the second and third lights, you get a result that is similar to the lighting on PS1. The original lighting seems to still be in there. You can see how the light pinches on Cloud's forehead and the front of his pants, or how the gradients in his hair travel in similar directions. (The lighting is still much darker though, so it's not a complete solution.)

![Cloud-Comparison-3](https://user-images.githubusercontent.com/30498581/126481695-05a232c6-0302-4b19-8f88-b787a35ecf2f.png)

If PS1 support was there, I could see how the second and third lights affect Cloud on PS1. Hopefully there's someone out there who can look into this in the future!

**Comment by myst6re** [comment]
I pushed some changes to edit global light, directional lights and model scale on PS version
When available, can you try this build? https://ci.appveyor.com/project/myst6re/makoureactor/builds/40272467/job/koj13viu33u21fe7/artifacts

**Comment by HeyItsLollie** [comment]
It works! Thank you for adding editable properties for the lighting, that alone helps a lot. 🙌

**Comment by myst6re** [comment]
Remaining tasks moved to another issue. Closing this ticket .
