### ISSUE TITLE
Window.bin file created by Makou Reactor breaks FFNx soft reset.

### ISSUE THREAD

**Issue by chrcoluk** [myst6re/makoureactor#126]
Hi

I made 3 Window.bin files for ESUI, ECHOS and Phoenix Avatars, if any of the three are active in game, pressing ctrl-r in game locks up the game.

When I resaved them using the hack7 tool even without editing any values it works with soft reset again.

Using makou reactor 1.8.5 on Windows 10.

I can provide both Window.bin's for comparison.

[windowbinfiles.zip](https://github.com/myst6re/makoureactor/files/7135869/windowbinfiles.zip)

**Comment by myst6re** [comment]
Thanks for the report.

There are two differences in the files you provided:

- The compression is not exactly the same
- A whole section is missing in the file from makou

**Comment by myst6re** [comment]
Does FFNx still crashes with this patched window.bin?
[Window.bin-makoureactor-patched.zip](https://github.com/myst6re/makoureactor/files/7387405/Window.bin-makoureactor-patched.zip)

**Comment by chrcoluk** [comment]
Hi, sorry just noticed this, I will test it and let you know. :)
