### ISSUE TITLE
Missing ff7tk.dll in continous builds

### ISSUE THREAD

**Issue by julianxhokaxhiu** [myst6re/makoureactor#139]
Upon trying to download and run the win64 QT6 build of Makou from the CI tag, once extracting the Zip and running Makou it brings an error saying that it cannot find `ff7tk.dll`.

Didn't try other combinations, so might be it is fixed in some releases but not this one.

Thank you in advance

**Comment by sithlord48** [comment]
Should be fixed by #140

**Comment by myst6re** [comment]
Not entirely, now ff7tk depends on:
Qt6Core5Compat.dll
Qt6Xml.dll
Qt6Qml.dll

even if I don't require it in my code :/

**Comment by julianxhokaxhiu** [comment]
I'm having the same issue, some more DLLs are missing now, although it doesn't complain anymore about `ff7tk.dll`.
