### ISSUE TITLE
Ctrl+K shortcut for Tutorials/Sounds does not work

### ISSUE THREAD

**Issue by futcharist** [myst6re/makoureactor#146]
As mentioned by the title, when pressing Ctrl+K to open tutorials/sound window, there is no response from the program.
Ctrl+F functions perfectly for Find, as well as every other shortcut listed.

**Comment by futcharist** [comment]
New discovery, I'm sure myst6re has already caught it: Ctrl+K functions if the program is newly opened and does not have an flevel loaded for editing.

**Comment by myst6re** [comment]
The keyboard shortcut was used in two different menus. I pushed a fix for the next version, thanks you :)
