### ISSUE TITLE
New crash issue 

### ISSUE THREAD

**Issue by EpicStoffer** [myst6re/makoureactor#152]
I've fond another consistent crash issue with Makou Reactor. 

To replicate it, just do the following: 

Edit several fields (it's enough to just press to edit a field name, and then *not* edit it, as Makou will think that you've made a change), and then just attempt to quicksave. 

Makou will crash everytime^

**Comment by EpicStoffer** [comment]
I'm unsure of the exact number of multiple field edits requires, to crash when you attempt to save afterwards. But somewhere around 6 edits, should be more than enough.

**Comment by myst6re** [comment]
I prepare a fix for the crash for the 1.8.6 version, but the behavior when you rename a field is incorrect.

See #154
