### ISSUE TITLE
Can't switch to 16-bit vars under If...then

### ISSUE THREAD

**Issue by PureMindGames** [myst6re/makoureactor#198]
I needed to change a (or else goto label x) to another label for a If '$Gamemoment' however it wouldn't let me switch to 16-bit had to go back to 1.8.6 which just let me save without changing the (else goto label x) anyway while 2.0.0 gave an error

**Comment by myst6re** [comment]
Just to be sure, can you test with the last unstable build?
https://github.com/myst6re/makoureactor/releases/tag/continuous

**Comment by myst6re** [comment]
No problem!
