### ISSUE TITLE
Copy-pasting KAWAI code for changing characters' eyes causes Makou to crash

### ISSUE THREAD

**Issue by Bjburn2689** [myst6re/makoureactor#201]
**Describe the bug**
When you copy paste a statement that changes the state of the characters' eyes (KAWAI 7), Makou will crash every time.

**To Reproduce**
Either go to a scene with such a statement or otherwise create such a statement in the field script, and then copy and try to paste it. Should crash every time.

**Expected behavior**
Ideally it would just paste the command and not crash.

**Additional context**
This wasn't a problem in Makou before version 2.0. When I want to add facial expressions to scenes in-bulk at the moment I revert back to 1.8.5.

**Comment by myst6re** [comment]
Fixed with commit 2a61513
