### ISSUE TITLE
Launch custom ff7 command with parameters

### ISSUE THREAD

**Issue by myst6re** [myst6re/makoureactor#26]
On Windows, FF7 is well detected. But on other OSes, WINE is always used to start FF7. Sometimes we want to use our own command to start the game, with Crossover for example (MacOS).

**Comment by sithlord48** [comment]
Mac os Should work correctly via the exsisting methods as of  https://github.com/myst6re/makoureactor/commit/b9b31883f155671b9d669eb9469fa831012b651f
