### ISSUE TITLE
Remove GLUT

### ISSUE THREAD

**Issue by myst6re** [myst6re/makoureactor#4]
GLUT is outdated and was removed from Qt. Right now to compile Makou Reactor with Qt 5 we can either add GLUT dependency, or do not use GLUT anymore. I prefer the second choice, but to replace with what?

**Comment by TurBoss** [comment]
http://doc.qt.io/qt-5/qtgui-index.html#opengl-and-opengl-es-integration
is this useful?

**Comment by sithlord48** [comment]
i would say for now lets get makou building on qt5 with GLUT and we can replace it after the porting is done that way we can be sure nothing is broken after the port.

**Comment by myst6re** [comment]
Fixed by #93
