### ISSUE TITLE
Error: Could not decode "file" with "UTF-8"-encodig. Editing not posible.

### ISSUE THREAD

**Issue by TurBoss** [myst6re/makoureactor#5]
this is what QtCreator whit Qt 5.5.1 shows when I try to edit any file

**Comment by sithlord48** [comment]
please be sure you are using the develop branch . the master branch does not have utf-8 files since myst would rather us work off the develop branch.

**Comment by TurBoss** [comment]
ok I'm on master
thank you

**Comment by sithlord48** [comment]
your welcome . i often forget about the develop branch myself . im used to working off master myself.

**Comment by myst6re** [comment]
For info, I use a git-flow-like branching model http://nvie.com/posts/a-successful-git-branching-model/
