### ISSUE TITLE
Beacause retranslation option. 

### ISSUE THREAD

**Issue by DLPB2** [myst6re/makoureactor#55]
Beacause uses certain characters on the font so that the PC version can have PS1 controller icons.  Any chance of adding this option?

Up = BE
Down = BF
Left = 93
Right = 94
X = 95
Square = 96
Triange = 97
Circle = 98
L1 = 99
R1 = 9A
L2 = 9B
R2 = 9C
Select = 81
Start = 82 

and a love heart (♥) at

80 and 83.

**Comment by myst6re** [comment]
I can add a "special characters map" with every possible characters in it. It will shows the texture from window.bin and provide a way to select a specific character.

**Comment by DLPB2** [comment]
If the window.bin texture is loaded and the character spacing data also in window.bin is used, this will solve the issue entirely - apart from the fact that text would need tags for retranslation such as {C} {X} {T} {S} as opposed to the font hex.  For example {C} would show Circle, which is 0x98.  It depends how you are doing it.  It would just make editing the game much easier for people who use retranslation.

Dan

**Comment by sithlord48** [comment]
Invalid as is. 
See: #85
