### ISSUE TITLE
Deleted data being left in the file

### ISSUE THREAD

**Issue by DLPB2** [myst6re/makoureactor#62]
When code is deleted from a field, the data is still left inside the file. The file will get larger and larger. The actual code will no longer show up in Makou or be seen by the game, probably because the header data is correct and so on. 

Please see the file I have uploaded here ("farm"):
https://drive.google.com/file/d/0B43luAxFZKC-OTczYVEwem0tdmc/view?usp=sharing

In testing, I added hundreds of Addition operations.  You can see the data is still here, and the uncompressed field is, therefore, huge.

Junk data needs to be deleted when not referenced. The fix can hopefully repair files like the one I have uploaded.

**Comment by myst6re** [comment]
So if I remove your operations, the file size will not decrease?

**Comment by DLPB2** [comment]
In that file uploaded, I have already removed the operations.  But the data I deleted is still in there.  A lot of Addition operations.  It's 559 KB instead of around 288 normal.

**Comment by myst6re** [comment]
And I guess you don't see the operations in Makou. (I see them when I import your file, I'll try another way)

**Comment by DLPB2** [comment]
There are still some Addition operations in the file I uploaded that will show up - but nowhere near enough to cause a 200 KB increase in file size.

**Comment by DLPB2** [comment]
Th correct addition operations should only be in Group 11, untitled Main and Script 1.  Group 11 is the last group showing in Makou Reactor for me witht his file - but still 200 KB larger than a normal farm file.

**Comment by DLPB2** [comment]
Check the hex of that file and see if it only has 100 or so addition instructions.  If it does, then I am in error.

**Comment by myst6re** [comment]
Farm size:
Normal compressed: 285 334 B, uncompressed: 427 730 B
DLPB version compressed: 301 080 B, uncompressed: 559 253 B

131 KB is really much more! No there must be something wrong, I may look outside the scripts section.

**Comment by myst6re** [comment]
Well I see where is the crap, but I really don't know why it happens.
The section 1 of your file is correct from the begining until the AKAO part. On this part, the AKAOs aren't here, instead there is the remaining deleted operations of the old version, followed by texts (again) and AKAOs. It is like I use the old big version of your file, then overprint scripts and texts above, without resizing.

**Comment by DLPB2** [comment]
Is the original data (a huge number of Addition operations) still present in there?>

**Comment by myst6re** [comment]
In the crap part, after the first texts part, yes.

**Comment by DLPB2** [comment]
If so, I am not sure why it isn't being deleted.  I can only think that when flevel is saved, it saves the junk and amends the headers and so on.  You can probably replicate it by adding hundreds of instructions, saving, deleting them, saving again.

**Comment by DLPB2** [comment]
Had a chat with Luksy.  My test to test the limit of the ff7 field module may have broken the script.  It seems that data is being deleted, but not when it exceeds the 2 byte maximum header size. For example, adding thousands of operations that cause a very large script.

Makou needs to check and refuse to save when the script becomes too large to support.

**Comment by myst6re** [comment]
I can do that. Not so strange cause I separated opening and saving of AKAO/tuto section from scripts/texts section, that's why if nothing change in sounds or tutos, I reuse old data from the AKAO part of the section 1.

**Comment by myst6re** [comment]
I added enough tests when the section 1 is saved.

There is still more to do:
 - Explicit error message when the user save its work
 - Improving existing compilation error (when the script reached max limit, ie scripts size > 65535) according to texts size and akao/tutos size.
