### ISSUE TITLE
Crash will occur if loading flevel.lgp a second time

### ISSUE THREAD

**Issue by DLPB2** [myst6re/makoureactor#65]
When flevel.lgp is loaded, everything will work fine and editing and saving will function correctly.  But if opening another flevel, makou will become unstable and crash when editing or saving. This is hard to replicate every time, but if you save a lot of edits, then open another  flevel, it should occur more often.

**Comment by sithlord48** [comment]
Unable to reproduce 1.8.0

**Comment by myst6re** [comment]
Also fixed
