### ISSUE TITLE
Incorrect search for bit test operations.

### ISSUE THREAD

**Issue by DLPB2** [myst6re/makoureactor#75]
For example, searching for

Var [3][161] Bit Test 2

You will get results such as

If Var[3][161] & 2 (else goto label 1)

It's seeing & 2 as bit 2 

when, in fact, bit 2 is & 4. 

Bit 0 is &1
Bit 1 is &2

and so on...

It is probably doing same with all logical operations.

**Comment by DLPB2** [comment]
Any news on this one?

**Comment by myst6re** [comment]
Not at the moment sorry, but I acknowledge the issue :)

**Comment by myst6re** [comment]
BitOn, BitOr and BitXor should be fixed now, BitOn and BitOff were already good!
