### ISSUE TITLE
Request - New Opcode 1C - Write to any memory address via array

### ISSUE THREAD

**Issue by DLPB2** [myst6re/makoureactor#79]
This opcode is a request from Sega Chief.  I've implemented it in my DLL:

Opcode 1C
Argument 1: Memory address 0-FFFFFFFF  - Total size: 4 bytes
Argument 2: Size of array.  This is added by Makou Reactor based on Argument 3. Total size: 1 Byte
Argument 3: Array of bytes.  Variable size - maximum size: 128 bytes.

User will see 

Memory address:
Array:

They will enter hexadecimal memory address into Memory Address field and then add an array in the array field. An example may be

Memory Address:  52D111
Array: FF FF FF 22 1D  2D 3D 44

Size is invisible to the user.  Makou would add argument 2 at the end - Size in this case would be 8.

**Comment by myst6re** [comment]
Done
